services:
  theoria-tests:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: theoria-dev
    volumes:
      - .:/app
    working_dir: /app
    # Override default command to allow interactive usage
    command: run-tests

  # Interactive development shell
  theoria-dev:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: theoria-dev-shell
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true
